### PR TITLE
Cuda

### PR DESCRIPTION
**Pull request by Mizerb**

### CODE REVIEW

**Comment by ibaned** [comment]
I'll have to wait until Friday to look this over

**Comment by ibaned** [comment]
reflect_down is done a bit backwards.
This is the loop that should be parallel:

https://github.com/ibaned/omega_h/blob/master/reflect_down.c#L64

Everything in the body of that loop can go into a kernel.
(Unfortunately it may end up having tons of arguments... oh well).
The helpers up here just need __device__ __host__:

https://github.com/ibaned/omega_h/blob/master/reflect_down.c#L9

**Comment by Mizerb** [comment]
That was done intentionally. I didn't know if nhighs would be a sufficient
number for CUDA to be effective, though I suspect that the copy,
copy_except, and intercept would also not be sufficient. I'll rewrite it
the other way, I had performance concerns if I just inserted the general
for loop into a kernel.

**Comment by Mizerb** [comment]
Ok, it's redone. Seems to be working on the serial end. I am currently unable to test the CUDA functionality.

**Comment by ibaned** [comment]
Cool. Yes, I've refactored many things, even which functions get called by mesh_ask_down. The main changes are that we're going to use full topology more (edges and triangles in a 3D mesh, edges in a 2D mesh), and the MPI parallel system getting to be stable. If you're going to test reflect_down, you'll have to make sure that bridge_dual_graph and derive_sides are also in place:

https://github.com/ibaned/omega_h/blob/master/mesh.c#L165

We'll get more coordinated as the semester starts and I stop redesigning internals.

**Pull request merged**
