### PR TITLE
Write parents arrays to file for hypercubes

### PR DESCRIPTION
**Pull request by bgranzow**
Might make sense to bump the file version number with this change, but I couldn't figure out how to do that.

### CODE REVIEW

**Comment by ibaned** [comment]
Wouldn't it be as simple as looping over all dimensions and making sure none of their parents arrays exist?

**Comment by ibaned** [comment]
If it is I would add a `mesh.has_any_parents()` that does this.

**Comment by bgranzow** [comment]
That is reasonable for writing, I think. For reading, you don't know if the mesh is an AMR mesh unless you actually encounter a parents array in the file. Does the logic for reading need to change to account for this?

**Comment by ibaned** [comment]
@bgranzow yea, you can add code to always write a single "boolean" (maybe an `I8` type) that is one or zero for AMR or not. That much is fine to always have in the file, then based on that read them or not.

**Pull request merged**
